// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: User.proto

package com.sof.protobuffer;

public final class UserProtos {
  private UserProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:User)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 userid = 1;</code>
     */
    int getUserid();

    /**
     * <code>string uname = 2;</code>
     */
    java.lang.String getUname();
    /**
     * <code>string uname = 2;</code>
     */
    com.google.protobuf.ByteString
        getUnameBytes();

    /**
     * <code>string password = 3;</code>
     */
    java.lang.String getPassword();
    /**
     * <code>string password = 3;</code>
     */
    com.google.protobuf.ByteString
        getPasswordBytes();

    /**
     * <code>int32 age = 4;</code>
     */
    int getAge();

    /**
     * <code>.User.Sex sex = 5;</code>
     */
    int getSexValue();
    /**
     * <code>.User.Sex sex = 5;</code>
     */
    com.sof.protobuffer.UserProtos.User.Sex getSex();
  }
  /**
   * Protobuf type {@code User}
   */
  public  static final class User extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:User)
      UserOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use User.newBuilder() to construct.
    private User(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private User() {
      userid_ = 0;
      uname_ = "";
      password_ = "";
      age_ = 0;
      sex_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private User(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              userid_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              uname_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              password_ = s;
              break;
            }
            case 32: {

              age_ = input.readInt32();
              break;
            }
            case 40: {
              int rawValue = input.readEnum();

              sex_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sof.protobuffer.UserProtos.internal_static_User_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sof.protobuffer.UserProtos.internal_static_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sof.protobuffer.UserProtos.User.class, com.sof.protobuffer.UserProtos.User.Builder.class);
    }

    /**
     * Protobuf enum {@code User.Sex}
     */
    public enum Sex
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>FEMALE = 0;</code>
       */
      FEMALE(0),
      /**
       * <code>MALE = 1;</code>
       */
      MALE(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>FEMALE = 0;</code>
       */
      public static final int FEMALE_VALUE = 0;
      /**
       * <code>MALE = 1;</code>
       */
      public static final int MALE_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Sex valueOf(int value) {
        return forNumber(value);
      }

      public static Sex forNumber(int value) {
        switch (value) {
          case 0: return FEMALE;
          case 1: return MALE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Sex>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Sex> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Sex>() {
              public Sex findValueByNumber(int number) {
                return Sex.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.sof.protobuffer.UserProtos.User.getDescriptor().getEnumTypes().get(0);
      }

      private static final Sex[] VALUES = values();

      public static Sex valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Sex(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:User.Sex)
    }

    public static final int USERID_FIELD_NUMBER = 1;
    private int userid_;
    /**
     * <code>int32 userid = 1;</code>
     */
    public int getUserid() {
      return userid_;
    }

    public static final int UNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object uname_;
    /**
     * <code>string uname = 2;</code>
     */
    public java.lang.String getUname() {
      java.lang.Object ref = uname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uname_ = s;
        return s;
      }
    }
    /**
     * <code>string uname = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUnameBytes() {
      java.lang.Object ref = uname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PASSWORD_FIELD_NUMBER = 3;
    private volatile java.lang.Object password_;
    /**
     * <code>string password = 3;</code>
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        password_ = s;
        return s;
      }
    }
    /**
     * <code>string password = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 4;
    private int age_;
    /**
     * <code>int32 age = 4;</code>
     */
    public int getAge() {
      return age_;
    }

    public static final int SEX_FIELD_NUMBER = 5;
    private int sex_;
    /**
     * <code>.User.Sex sex = 5;</code>
     */
    public int getSexValue() {
      return sex_;
    }
    /**
     * <code>.User.Sex sex = 5;</code>
     */
    public com.sof.protobuffer.UserProtos.User.Sex getSex() {
      @SuppressWarnings("deprecation")
      com.sof.protobuffer.UserProtos.User.Sex result = com.sof.protobuffer.UserProtos.User.Sex.valueOf(sex_);
      return result == null ? com.sof.protobuffer.UserProtos.User.Sex.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (userid_ != 0) {
        output.writeInt32(1, userid_);
      }
      if (!getUnameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, uname_);
      }
      if (!getPasswordBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, password_);
      }
      if (age_ != 0) {
        output.writeInt32(4, age_);
      }
      if (sex_ != com.sof.protobuffer.UserProtos.User.Sex.FEMALE.getNumber()) {
        output.writeEnum(5, sex_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (userid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, userid_);
      }
      if (!getUnameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, uname_);
      }
      if (!getPasswordBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, password_);
      }
      if (age_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, age_);
      }
      if (sex_ != com.sof.protobuffer.UserProtos.User.Sex.FEMALE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, sex_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.sof.protobuffer.UserProtos.User)) {
        return super.equals(obj);
      }
      com.sof.protobuffer.UserProtos.User other = (com.sof.protobuffer.UserProtos.User) obj;

      boolean result = true;
      result = result && (getUserid()
          == other.getUserid());
      result = result && getUname()
          .equals(other.getUname());
      result = result && getPassword()
          .equals(other.getPassword());
      result = result && (getAge()
          == other.getAge());
      result = result && sex_ == other.sex_;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserid();
      hash = (37 * hash) + UNAME_FIELD_NUMBER;
      hash = (53 * hash) + getUname().hashCode();
      hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
      hash = (53 * hash) + getPassword().hashCode();
      hash = (37 * hash) + AGE_FIELD_NUMBER;
      hash = (53 * hash) + getAge();
      hash = (37 * hash) + SEX_FIELD_NUMBER;
      hash = (53 * hash) + sex_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.sof.protobuffer.UserProtos.User parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sof.protobuffer.UserProtos.User parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sof.protobuffer.UserProtos.User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sof.protobuffer.UserProtos.User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sof.protobuffer.UserProtos.User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sof.protobuffer.UserProtos.User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sof.protobuffer.UserProtos.User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sof.protobuffer.UserProtos.User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sof.protobuffer.UserProtos.User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.sof.protobuffer.UserProtos.User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sof.protobuffer.UserProtos.User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sof.protobuffer.UserProtos.User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.sof.protobuffer.UserProtos.User prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code User}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:User)
        com.sof.protobuffer.UserProtos.UserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.sof.protobuffer.UserProtos.internal_static_User_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sof.protobuffer.UserProtos.internal_static_User_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.sof.protobuffer.UserProtos.User.class, com.sof.protobuffer.UserProtos.User.Builder.class);
      }

      // Construct using com.sof.protobuffer.UserProtos.User.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        userid_ = 0;

        uname_ = "";

        password_ = "";

        age_ = 0;

        sex_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sof.protobuffer.UserProtos.internal_static_User_descriptor;
      }

      @java.lang.Override
      public com.sof.protobuffer.UserProtos.User getDefaultInstanceForType() {
        return com.sof.protobuffer.UserProtos.User.getDefaultInstance();
      }

      @java.lang.Override
      public com.sof.protobuffer.UserProtos.User build() {
        com.sof.protobuffer.UserProtos.User result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.sof.protobuffer.UserProtos.User buildPartial() {
        com.sof.protobuffer.UserProtos.User result = new com.sof.protobuffer.UserProtos.User(this);
        result.userid_ = userid_;
        result.uname_ = uname_;
        result.password_ = password_;
        result.age_ = age_;
        result.sex_ = sex_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sof.protobuffer.UserProtos.User) {
          return mergeFrom((com.sof.protobuffer.UserProtos.User)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.sof.protobuffer.UserProtos.User other) {
        if (other == com.sof.protobuffer.UserProtos.User.getDefaultInstance()) return this;
        if (other.getUserid() != 0) {
          setUserid(other.getUserid());
        }
        if (!other.getUname().isEmpty()) {
          uname_ = other.uname_;
          onChanged();
        }
        if (!other.getPassword().isEmpty()) {
          password_ = other.password_;
          onChanged();
        }
        if (other.getAge() != 0) {
          setAge(other.getAge());
        }
        if (other.sex_ != 0) {
          setSexValue(other.getSexValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.sof.protobuffer.UserProtos.User parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.sof.protobuffer.UserProtos.User) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int userid_ ;
      /**
       * <code>int32 userid = 1;</code>
       */
      public int getUserid() {
        return userid_;
      }
      /**
       * <code>int32 userid = 1;</code>
       */
      public Builder setUserid(int value) {
        
        userid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 userid = 1;</code>
       */
      public Builder clearUserid() {
        
        userid_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object uname_ = "";
      /**
       * <code>string uname = 2;</code>
       */
      public java.lang.String getUname() {
        java.lang.Object ref = uname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          uname_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string uname = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUnameBytes() {
        java.lang.Object ref = uname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string uname = 2;</code>
       */
      public Builder setUname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        uname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string uname = 2;</code>
       */
      public Builder clearUname() {
        
        uname_ = getDefaultInstance().getUname();
        onChanged();
        return this;
      }
      /**
       * <code>string uname = 2;</code>
       */
      public Builder setUnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        uname_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object password_ = "";
      /**
       * <code>string password = 3;</code>
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          password_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string password = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string password = 3;</code>
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string password = 3;</code>
       */
      public Builder clearPassword() {
        
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <code>string password = 3;</code>
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        password_ = value;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <code>int32 age = 4;</code>
       */
      public int getAge() {
        return age_;
      }
      /**
       * <code>int32 age = 4;</code>
       */
      public Builder setAge(int value) {
        
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 age = 4;</code>
       */
      public Builder clearAge() {
        
        age_ = 0;
        onChanged();
        return this;
      }

      private int sex_ = 0;
      /**
       * <code>.User.Sex sex = 5;</code>
       */
      public int getSexValue() {
        return sex_;
      }
      /**
       * <code>.User.Sex sex = 5;</code>
       */
      public Builder setSexValue(int value) {
        sex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.User.Sex sex = 5;</code>
       */
      public com.sof.protobuffer.UserProtos.User.Sex getSex() {
        @SuppressWarnings("deprecation")
        com.sof.protobuffer.UserProtos.User.Sex result = com.sof.protobuffer.UserProtos.User.Sex.valueOf(sex_);
        return result == null ? com.sof.protobuffer.UserProtos.User.Sex.UNRECOGNIZED : result;
      }
      /**
       * <code>.User.Sex sex = 5;</code>
       */
      public Builder setSex(com.sof.protobuffer.UserProtos.User.Sex value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        sex_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.User.Sex sex = 5;</code>
       */
      public Builder clearSex() {
        
        sex_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:User)
    }

    // @@protoc_insertion_point(class_scope:User)
    private static final com.sof.protobuffer.UserProtos.User DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.sof.protobuffer.UserProtos.User();
    }

    public static com.sof.protobuffer.UserProtos.User getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<User>
        PARSER = new com.google.protobuf.AbstractParser<User>() {
      @java.lang.Override
      public User parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new User(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<User> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<User> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.sof.protobuffer.UserProtos.User getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_User_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_User_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nUser.proto\"y\n\004User\022\016\n\006userid\030\001 \001(\005\022\r\n\005" +
      "uname\030\002 \001(\t\022\020\n\010password\030\003 \001(\t\022\013\n\003age\030\004 \001" +
      "(\005\022\026\n\003sex\030\005 \001(\0162\t.User.Sex\"\033\n\003Sex\022\n\n\006FEM" +
      "ALE\020\000\022\010\n\004MALE\020\001B!\n\023com.sof.protobufferB\n" +
      "UserProtosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_User_descriptor,
        new java.lang.String[] { "Userid", "Uname", "Password", "Age", "Sex", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
